export enum MangaStatus {
  ONGOING = 'ongoing',
  COMPLETED = 'completed',
  HIATUS = 'hiatus',
  CANCELLED = 'cancelled',
}

export const MangaStatusLabels: Record<MangaStatus, string> = {
  [MangaStatus.ONGOING]: 'Em andamento',
  [MangaStatus.COMPLETED]: 'Finalizado',
  [MangaStatus.HIATUS]: 'Hiato',
  [MangaStatus.CANCELLED]: 'Cancelado',
};

export enum ContentRating {
  SAFE = 'safe',
  SUGGESTIVE = 'suggestive',
  EROTICA = 'erotica',
  PORNOGRAPHIC = 'pornographic',
}

export const ContentRatingLabels: Record<ContentRating, string> = {
  [ContentRating.SAFE]: 'Livre',
  [ContentRating.SUGGESTIVE]: 'Sugestivo',
  [ContentRating.EROTICA]: 'Erótico',
  [ContentRating.PORNOGRAPHIC]: 'Pornográfico',
};

// Mapeamento de tags conhecidas para PT-BR
export const TagLabels: Record<string, string> = {
  "Action": "Ação",
  "Adventure": "Aventura",
  "Comedy": "Comédia",
  "Drama": "Drama",
  "Fantasy": "Fantasia",
  "Horror": "Terror",
  "Mystery": "Mistério",
  "Psychological": "Psicológico",
  "Romance": "Romance",
  "Sci-Fi": "Ficção Científica",
  "Slice of Life": "Cotidiano",
  "Sports": "Esportes",
  "Supernatural": "Sobrenatural",
  "Tragedy": "Tragédia",
  "Thriller": "Suspense",
  "Historical": "Histórico",
  "Martial Arts": "Artes Marciais",
  "Mecha": "Mecha",
  "Cooking": "Culinária",
  "Medical": "Médico",
  "Political": "Político",
  "School Life": "Vida Escolar",
  "Video Games": "Videogames",
  "Traditional Games": "Jogos Tradicionais",
  "Isekai": "Isekai",
  "Magical Girls": "Garotas Mágicas",
  "Aliens": "Alienígenas",
  "Animals": "Animais",
  "Crossdressing": "Crossdressing",
  "Delinquents": "Delinquentes",
  "Demons": "Demônios",
  "Genderswap": "Troca de Gênero",
  "Ghosts": "Fantasmas",
  "Gyaru": "Gyaru",
  "Harem": "Harém",
  "Incest": "Incesto",
  "Loli": "Loli",
  "Magic": "Magia",
  "Military": "Militar",
  "Monster Girls": "Garotas Monstro",
  "Monsters": "Monstros",
  "Music": "Música",
  "Ninja": "Ninja",
  "Office Workers": "Trabalhadores de Escritório",
  "Police": "Polícia",
  "Post-Apocalyptic": "Pós-Apocalíptico",
  "Reincarnation": "Reencarnação",
  "Reverse Harem": "Harém Inverso",
  "Samurai": "Samurai",
  "Shota": "Shota",
  "Superpowers": "Superpoderes",
  "Survival": "Sobrevivência",
  "Time Travel": "Viagem no Tempo",
  "Vampires": "Vampiros",
  "Villainess": "Vilã",
  "Zombies": "Zumbis",
  "Award Winning": "Premiado",
  "Doujinshi": "Doujinshi",
  "Oneshot": "Oneshot",
  "Long Strip": "Tira Longa",
  "Full Color": "Colorido",
  "User Created": "Criado pelo Usuário",
  "Anthology": "Antologia",
  "Web Comic": "Webtoon",
  "Fan Color": "Colorido por Fãs",
  "Self-Published": "Auto-publicado",
  "Official Colored": "Colorido Oficial",
};
